buri_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^get_quote/', include('get_quote.urls')),
	url(r'^home/', include('home.urls')),
	url(r'^', include('home.urls')),
	url(r'^netfleet/', include('netfleet.urls')),
	url(r'^', include('netfleet.urls')),
	url(r'^contactus/', include('contactus.urls')),
	url(r'^', include('contactus.urls')),
	url(r'^request_quote/', include('request_quote.urls')),
	url(r'^', include('request_quote.urls')),
]

contactus/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^contactus/$', views.ContactCreate.as_view(), name='contact_add'),
	#url(r'^quote/$', views.quote, name='quote'),
]

get_quote/urls.py
from django.conf.urls import url
from . import views

app_name = 'get_quote'

urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
	
	url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(), name='detail'),
	
	# /get_quote/client/add/
	url(r'client/add/$', views.ClientCreate.as_view(), name='client-add'),

	url(r'client/(?P<pk>[0-9]+)/$', views.ClientUpdate.as_view(), name='client-update'),

	url(r'client/(?P<pk>[0-9]+)/delete/$', views.ClientDelete.as_view(), name='client-delete'),
]

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^work_clients/$', views.work_clients, name='work_clients'),
]

netfleet/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^fleet/$', views.fleet, name='fleet'),
]

request_quote/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^request_quote/$', views.QuoteRequest.as_view(), name='quoteRequest'),
	#url(r'^quote/$', views.quote, name='quote'),
]

contactus/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Contact(models.Model):
	first_name = models.CharField(max_length=100)
	second_name = models.CharField(max_length=100)
	address = models.CharField(max_length=200)
	county = models.CharField(max_length=200)
	town = models.CharField(max_length=50)
	email = models.CharField(max_length=100)
	comment = models.TextField(max_length=500)
	
	def get_absolute_url(self):
		return reverse('contact_add')
		
	def __str__(self):
		return self.second_name + ' - ' + self.address + ' - ' + self.email
	

get_quote/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Client(models.Model):
	company = models.CharField(max_length=200)
	name = models.CharField(max_length=200)
	phone_num = models.IntegerField()
	address = models.CharField(max_length=300)
	email = models.CharField(max_length=200)
	
	def get_absolute_url(self):
		return reverse('get_quote:detail', kwargs={'pk':self.pk})
		
	def __str__(self):
		return self.company + ' - ' + self.name + ' - ' + self.email
	
class Commodity(models.Model):
	client = models.ForeignKey(Client, on_delete=models.CASCADE)
	commodity_type = models.CharField(max_length=200)
	quantity = models.CharField(max_length=300)
	packing_type = models.CharField(max_length=300)
	is_clear_forward = models.BooleanField(default=False)
	
	def __str__(self):
		return self.commodity_type + ' - ' + self.quantity
		
class Transport(models.Model):
	commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE)
	pick_from = models.CharField(max_length=300)
	deliver_to = models.CharField(max_length=300)
	
	

home/models.py
from django.db import models

# Create your models here.

netfleet/models.py
from django.db import models

# Create your models here.

request_quote/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Quote(models.Model):
	company = models.CharField(max_length=200)
	name = models.CharField(max_length=200)
	phone_num = models.IntegerField()
	address = models.CharField(max_length=300)
	email = models.CharField(max_length=200)
	commodity_type = models.CharField(max_length=200)
	quantity = models.CharField(max_length=300)
	packing_type = models.CharField(max_length=300)
	is_clear_forward = models.BooleanField(default=False)
	pick_from = models.CharField(max_length=300)
	deliver_to = models.CharField(max_length=300)
	
	def get_absolute_url(self):
		return reverse('quoteRequest')
		
	def __str__(self):
		return self.company + ' - ' + self.address + ' - ' + self.commodity_type

contactus/views.py
from .models import Contact
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class ContactCreate(CreateView):
    model = Contact
    fields = ['first_name','second_name','address','county','town','email','comment']
    template_name='contactus/contact_form.html'

get_quote/views.py
from django.views import generic 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Client

class IndexView(generic.ListView):
	template_name = "get_quote/index.html"
	context_object_name = "all_clients"
	
	def get_queryset(self):
		return Client.objects.all()
		
class DetailView(generic.DetailView):
	model = Client
	template_name = "get_quote/work_clients.html"
	
class ClientCreate(CreateView):
	model = Client
	fields = ['company','name','phone_num','address','email']
	
class ClientUpdate(UpdateView):
	model = Client
	fields = ['company','name','phone_num','address','email']
	
class ClientDelete(DeleteView):
	model = ClientCreate
	success_url = reverse_lazy('index.html')

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	return render(request, 'home/about.html')
	
def work_clients(request):
	return render(request, 'home/page.html')

netfleet/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	return render(request, 'netfleet/network.html')
	
def fleet(request):
	return render(request, 'netfleet/fleet.html')

request_quote/views.py
from .models import Quote
from django.views.generic.edit import CreateView

class QuoteRequest(CreateView):

	template_name = "request_quote/quote_form.html"
	model = Quote
	fields = ['commodity_type','packing_type','quantity','pick_from','deliver_to','is_clear_forward','company','name','phone_num','address','email']
	

contactus/templates/contactus/contact_form.html
{% extends 'home/base.html' %}

{% block body %}
<div class="container text-center">
	<form action="" method="post" class='aform'>{% csrf_token %}
		<h1>Contact Us</h1><br>
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>	
</div>
{% endblock%}
	

get_quote/templates/get_quote/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Buri</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'get_quote/style.css' %}" />
	<link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
	<nav class="navbar navbar-inverse">
	<div class="container-fluid">
	
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'get_quote:index' %}">Buri</a>
		</div>
	
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'get_quote:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Clients
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Commodities
					</a>
				</li>				
			</ul> 
			
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">search</button>
			</form>
			
			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="{%url 'get_quote:client-add' %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Request Quote
					</a>
				</li>
				
			</ul>
		</div>
	
	</div>
	</nav>
{% block body %}
{%endblock%}
</body>
</html>

get_quote/templates/get_quote/client_form.html
{% extends 'get_quote/base.html' %}
{% block title %} Request a quote {% endblock %}
{% block clients_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">

	<div class="row">
		
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
				
					<form class="form-horizontal" action="" method="post" enc >
						{% csrf_token %}
						{% include 'get_quote/form-template.html'%}
						<div class="form-group">
							<button type="submit" class="btn btn-success">submit</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	
	</div>

</div>
{% endblock %}

get_quote/templates/get_quote/detail.html
{%extends 'get_quote/base.html'%}

{%block body%}
<h1>{{client.company}}</h1>
<h3>{{client.name}}</h3>

	{% csrf_token %}
	{% for commodity in client.commodity_set.all %}
		{{ commodity.commodity_type }}
		{% if commodity.is_clear_forward %}
			<p> - cleared/forwarded </p>
		{% endif %}
		<br>
	{% endfor %}


{%endblock%}

get_quote/templates/get_quote/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{%endfor%}

get_quote/templates/get_quote/index.html
{%extends 'get_quote/base.html'%}

{% block body %}

	<h3>Here are all the clients<h3>
	<div class="row">
		{% for client in all_clients %}
		
			<div class="col-sm-4 col-lg-2">
				<div class="thumbnail">
				
					<div class="caption">
						<h2>{{ client.company }}</h2>
						<h4>{{ client.name }}</h4>
						
						<a href="{%url 'get_quote:detail' client.id %}" class="btn btn-primary btn-sm">View Details</a>
						
						<!-- delete -->
						<form action="{% url 'get_quote:client-delete' client.id %}" method="post" style="display: inline;">
							{% csrf_token %}
							<input type="hidden" name="album_id" value="{{ album.id }}"/>
							<button type="submit" class="btn btn-default btn-sm">
								<span class="glyphicon glyphicon-trash"></span>
						</form>
						
					</div>	
				</div>
			</div>
		{%endfor%}
	</div>
	
{% endblock %}

get_quote/templates/get_quote/work_clients.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Buri Transporters Company</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="css/buristyle.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><img src="images/buri_logo.jpg" id="logo"></a>
				<h1 class="navbar-text">Buri Transporters Company</h1>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="index.html">Home</a></li>
					<li><a href="#">Work/Clients</a></li>
					<li><a href="Network.html">Network</a></li>
					<li><a href="fleet.html">Fleet</a></li>
					<li><a href="#">Quotation</a></li>
					<li><a href="contact.html">Contact Us</a></li>
				</ul>
			</div>
		</div>
	</nav>

	

	<div class="container text-center">
		<div class="row">
			
			<h4>Work</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
			Sed vestibulum ligula justo, quis elementum est ornare vel. 
			Nulla posuere eros ac consequat eleifend. Vestibulum laoreet mauris a laoreet efficitur.
			Duis sodales eu leo ac varius. Maecenas non magna scelerisque, tempus eros ac, blandit orci.
			Phasellus commodo arcu quis dolor consequat facilisis. Ut tempor vitae lectus quis tristique.
			Nam consequat efficitur velit vitae bibendum. 
			Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque turpis risus, 
			consectetur a enim eget, porta ornare ex. Donec vulputate ligula quis gravida iaculis. 
			Ut id nisi id ligula pharetra lobortis. 
			Donec ultricies congue sapien, ac fermentum neque. 
			Nullam ut elementum tortor. Morbi malesuada mauris orci, vitae volutpat dui laoreet nec. </p>
			
			
			<h4>Clients</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
			Sed vestibulum ligula justo, quis elementum est ornare vel. 
			Nulla posuere eros ac consequat eleifend. Vestibulum laoreet mauris a laoreet efficitur.
			Duis sodales eu leo ac varius. Maecenas non magna scelerisque, tempus eros ac, blandit orci.
			Phasellus commodo arcu quis dolor consequat facilisis. Ut tempor vitae lectus quis tristique.
			Nam consequat efficitur velit vitae bibendum. 
			Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque turpis risus, 
			consectetur a enim eget, porta ornare ex. Donec vulputate ligula quis gravida iaculis. 
			Ut id nisi id ligula pharetra lobortis. 
			Donec ultricies congue sapien, ac fermentum neque. 
			Nullam ut elementum tortor. Morbi malesuada mauris orci, vitae volutpat dui laoreet nec.
			</p>
			
		</div>
	</div>

	<div class="footer navbar-fixed-bottom">
		<div class="row">
			<div class="col-sm-6">
				<h3>Contact Us</h3>
				<br>
				<h4>our address and contact info here</h4>
			</div>
			<div class="col-sm-3">
				<h3>Connect</h3>
				<a href="https://www.facebook.com/search/str/buri+transporters+company/keywords_search?ref=eyJzaWQiOiIwLjQ5MTcxODQyNTk1NzAwNzkiLCJxcyI6IkpUVkNKVEl5WW5WeWFTVXlNSFJ5WVc1emNHOXlkR1Z5Y3lVeU1HTnZiWEJoYm5rbE1qSWxOVVEiLCJndiI6ImJlZTA5ZjkzZmE3MzJjZmE1OWExY2I2ZDlmNDUwZDM4OTI0MjRlNDkiLCJlbnRfaWRzIjpbMzAyNDc5NTU2NjIxNzIyXX0" class="fa fa-facebook"></a> 
			</div>
			<div class="col-sm-3">
				<img src="images/buri_logo.jpg" id="logo">
			</div>
		</div>
	</div>
	
	
	
	</body>
</html>

home/templates/home/about.html
{% extends 'home/base.html' %}

{% block body %}

	<div class="container text-center">
		<div class="row">
			<h1>About</h1>
			<div class="col-md-6">
				<h4>Summary</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				Sed vestibulum ligula justo, quis elementum est ornare vel. 
				Nulla posuere eros ac consequat eleifend. Vestibulum laoreet mauris a laoreet efficitur.
				Duis sodales eu leo ac varius. Maecenas non magna scelerisque, tempus eros ac, blandit orci.
				Phasellus commodo arcu quis dolor consequat facilisis. Ut tempor vitae lectus quis tristique.
				Nam consequat efficitur velit vitae bibendum. 
				Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque turpis risus, 
				consectetur a enim eget, porta ornare ex. Donec vulputate ligula quis gravida iaculis. 
				Ut id nisi id ligula pharetra lobortis. 
				Donec ultricies congue sapien, ac fermentum neque. 
				Nullam ut elementum tortor. Morbi malesuada mauris orci, vitae volutpat dui laoreet nec. </p>
				
				
			</div>
			<div class="col-md-6">
				<h4>Products and Services</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
				Sed vestibulum ligula justo, quis elementum est ornare vel. 
				Nulla posuere eros ac consequat eleifend. Vestibulum laoreet mauris a laoreet efficitur.
				Duis sodales eu leo ac varius. Maecenas non magna scelerisque, tempus eros ac, blandit orci.
				Phasellus commodo arcu quis dolor consequat facilisis. Ut tempor vitae lectus quis tristique.
				Nam consequat efficitur velit vitae bibendum. 
				Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque turpis risus, 
				consectetur a enim eget, porta ornare ex. Donec vulputate ligula quis gravida iaculis. 
				Ut id nisi id ligula pharetra lobortis. 
				Donec ultricies congue sapien, ac fermentum neque. 
				Nullam ut elementum tortor. Morbi malesuada mauris orci, vitae volutpat dui laoreet nec.
				</p>
			</div>
		</div>
	</div>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Buri Transporters Company</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="{%static 'home/font-awesome/css/font-awesome.min.css'%}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
	<!-- <link rel='stylesheet' href="{% static 'home/css/bootstrap.min.css' %}" type="text/css"> -->
</head>

<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="index.html"><img src = "{% static 'home/images/buri_logo.jpg' %}" id="logo"></a>
				<h1 class="navbar-text">Buri Transporters Limited</h1>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-right">
					<li><a href='/home/'>Home</a></li>
					<li><a href='/work_clients/'>Work/Clients</a></li>
					<li><a href='/netfleet/'>Network</a></li>
					<li><a href='/fleet/'>Fleet</a></li>
					<li><a href='/contactus/'>Contact Us</a></li>
					<li><a href='/request_quote/'>Quotation</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	{% block body %}
	{% endblock %}
	
	<footer class="container-fluid text-center">
		<div class="row">
			<div class="col-sm-6">
				<h4>Contact Us</h3>
				
				<h4>our address and contact info here</h4>
			</div>
			<div class="col-sm-3">
				<h3>Connect</h3>
				<a href="https://www.facebook.com/buritransporterscompany/" class="fa fa-facebook"></a> 
			</div>
			<div class="col-sm-3">
				<img src = "{% static 'home/images/buri_logo.jpg' %}" id="logo">
			</div>
		</div>
		<!--<a href="#myPage" title="To Top">
		<span class="glyphicon glyphicon-chevron-up"></span>
		</a>
		<p>Bootstrap Theme Made By <a href="https://www.w3schools.com" title="Visit w3schools">www.w3schools.com</a></p>-->
	</footer>
	
	
	
</body>

</html>

home/templates/home/page.html
{% extends 'home/base.html' %}

{% block body %}

	<div class="container text-center">
		<div class="row">
			<br>
			<br>
			<h4>Work</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
			Sed vestibulum ligula justo, quis elementum est ornare vel. 
			Nulla posuere eros ac consequat eleifend. Vestibulum laoreet mauris a laoreet efficitur.
			Duis sodales eu leo ac varius. Maecenas non magna scelerisque, tempus eros ac, blandit orci.
			Phasellus commodo arcu quis dolor consequat facilisis. Ut tempor vitae lectus quis tristique.
			Nam consequat efficitur velit vitae bibendum. 
			Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque turpis risus, 
			consectetur a enim eget, porta ornare ex. Donec vulputate ligula quis gravida iaculis. 
			Ut id nisi id ligula pharetra lobortis. 
			Donec ultricies congue sapien, ac fermentum neque. 
			Nullam ut elementum tortor. Morbi malesuada mauris orci, vitae volutpat dui laoreet nec. </p>
			
			<br>
			<h4>Clients</h4>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
			Sed vestibulum ligula justo, quis elementum est ornare vel. 
			Nulla posuere eros ac consequat eleifend. Vestibulum laoreet mauris a laoreet efficitur.
			Duis sodales eu leo ac varius. Maecenas non magna scelerisque, tempus eros ac, blandit orci.
			Phasellus commodo arcu quis dolor consequat facilisis. Ut tempor vitae lectus quis tristique.
			Nam consequat efficitur velit vitae bibendum. 
			Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque turpis risus, 
			consectetur a enim eget, porta ornare ex. Donec vulputate ligula quis gravida iaculis. 
			Ut id nisi id ligula pharetra lobortis. 
			Donec ultricies congue sapien, ac fermentum neque. 
			Nullam ut elementum tortor. Morbi malesuada mauris orci, vitae volutpat dui laoreet nec.
			</p>
			
		</div>
	</div>

{% endblock %}

netfleet/templates/netfleet/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Buri Transporters Company</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="font-awesome/css/font-awesome.min.css"/>
	<link rel="stylesheet" type="text/css" href="css/buristyle.css"/>
	<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
	<!-- <link rel='stylesheet' href="{% static 'home/css/bootstrap.min.css' %}" type="text/css"> -->
</head>

<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="index.html"><img src = "{% static 'home/images/buri_logo.jpg' %}" id="logo"></a>
				<h1 class="navbar-text">Buri Transporters Company</h1>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-right">
					<li><a href='/home/'>Home</a></li>
					<li><a href='/work_clients/'>Work/Clients</a></li>
					<li><a href="Network.html">Network</a></li>
					<li><a href="fleet.html">Fleet</a></li>
					<li><a href="#">Quotation</a></li>
					<li><a href="contact.html">Contact Us</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<div class="footer navbar-fixed-bottom">
		<div class="row">
			<div class="col-sm-6">
				<h4>Contact Us</h3>
				<br>
				<h4>our address and contact info here</h4>
			</div>
			<div class="col-sm-3">
				<h3>Connect</h3>
				<a href="https://www.facebook.com/search/str/buri+transporters+company/keywords_search?ref=eyJzaWQiOiIwLjQ5MTcxODQyNTk1NzAwNzkiLCJxcyI6IkpUVkNKVEl5WW5WeWFTVXlNSFJ5WVc1emNHOXlkR1Z5Y3lVeU1HTnZiWEJoYm5rbE1qSWxOVVEiLCJndiI6ImJlZTA5ZjkzZmE3MzJjZmE1OWExY2I2ZDlmNDUwZDM4OTI0MjRlNDkiLCJlbnRfaWRzIjpbMzAyNDc5NTU2NjIxNzIyXX0" class="fa fa-facebook"></a> 
			</div>
			<div class="col-sm-3">
				<img src = "{% static 'home/images/buri_logo.jpg' %}" id="logo">
			</div>
		</div>
	</div>
	
	{% block body %}
	{% endblock %}
	
</body>

</html>

netfleet/templates/netfleet/network.html
{% extends 'home/base.html' %}

{% block body %}

{% load staticfiles%}
	
	<div class="container text-center">
		<h1>Network</h1>
		<div class="row">
			<img src="{% static 'home/images/network.png' %}">
			
		</div>
	</div>

{% endblock %}

request_quote/templates/request_quote/quote_form.html
{% extends 'home/base.html' %}

{% block body %}

{% load staticfiles%}
<div class="container text-center">
	<form action="" method="post" class='aform'>{% csrf_token %}
		<h1>Request a Quote</h1><br>
		{{ form.as_p }}
		<input type="submit" value="Sumbit" />
	</form>
</div>
{% endblock%}